development: &development
  adapter: postgresql
  database: f2yd_rails_development
  username: user
  password: password
  host:     localhost
  schema_search_path: public
  min_messages: warning

test:
  <<: *development
  database: f2yd_rails_test

production:
  <<: *development
  database: f2yd_rails_production